# Generated by Django 2.2.16 on 2022-08-11 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(auto_created=True, default=uuid.UUID('356afa96-064c-4e3a-a618-ce2e6becafa2'), max_length=50, unique=True),
        ),
    ]
