# Generated by Django 2.2.16 on 2022-08-11 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220812_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(auto_created=True, default=uuid.UUID('7fd1d6ca-b391-4248-83d3-393b0da9f24f'), max_length=50),
        ),
    ]
